mysite/main/urls.py
from django.urls import path

from . import views as main_view

urlpatterns = [
    path('', main_view.index, name='index'),
    path('<str:platform>/', main_view.main_platform, name='main_platform'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls'), name="index"),
    path("admin/", admin.site.urls),
    path('users/', include('users.urls'), name='users')
]

mysite/users/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path

from . import views as users_view

app_name = 'users'
urlpatterns = [
    path('login/', users_view.CustomLoginView.as_view(), name="login"),
    path('logout/', auth_view.LogoutView.as_view(next_page='/'), name="logout"),
    path('signup/', users_view.signup, name='signup')
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from products.models import ProductTable
from users.models import UserMLResult


def index(request):
    if request.user.is_authenticated:
        return redirect('main_platform', platform='musinsa')
    return render(request, 'main/index.html')


def main_platform(request, platform):
    if request.user.is_authenticated:
        gender = request.user.gender
        top = ProductTable.get_product_filter_by_gender(platform, 'top', gender)[:10]
        bottom = ProductTable.get_product_filter_by_gender(platform, 'bottom', gender)[:10]

        # 사용자에 대한 ML 결과 가져오기
        ml_results = UserMLResult.objects.filter(user=request.user).select_related('product')

        # 제품별로 학습 결과 매핑
        top_results = {result.product.product_name: result for result in ml_results if result.product.category == 'top'}
        bottom_results = {result.product.product_name: result for result in ml_results if
                          result.product.category == 'bottom'}

        # top과 bottom 리스트에 학습 결과를 추가
        top_with_results = []
        for product in top:
            result = top_results.get(product.product_name)
            top_with_results.append({
                'product': product,
                'size': result.size if result else product.size,
                'score': convert_to_score(result.score) if result else None,
            })

        bottom_with_results = []
        for product in bottom:
            result = bottom_results.get(product.product_name)
            bottom_with_results.append({
                'product': product,
                'size': result.size if result else product.size,
                'score': convert_to_score(result.score) if result else None,
            })

        return render(request, 'main/logged_in.html', {
            'top': top_with_results,
            'bottom': bottom_with_results,
            'gender': gender
        })
    else:
        women_top = ProductTable.get_product_filter_by_gender(platform, 'top', 'female')[:10]
        women_bottom = ProductTable.get_product_filter_by_gender(platform, 'bottom', 'female')[:10]
        men_top = ProductTable.get_product_filter_by_gender(platform, 'top', 'male')[:10]
        men_bottom = ProductTable.get_product_filter_by_gender(platform, 'bottom', 'male')[:10]
        return render(request, 'main/logged_out.html',
                      {'women_top': women_top, 'women_bottom': women_bottom, 'men_top': men_top,
                       'men_bottom': men_bottom})


def convert_to_score(percentage):
    # 0% ~ 100%의 수치를 50 ~ 100으로 변환
    min_score = 50
    max_score = 100

    # 비율을 점수로 변환
    score = min_score + (percentage * (max_score - min_score))
    return round(score, 2)

mysite/main/templates/main/index.html
<!doctype html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>의류 추천 사이트, otto</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
</head>

<body>
<div class="hero">
    <div class="left-content">
        <header>
            <a href="/" class="home">
                <img src="{% static 'main/images/otto_logo1.png' %}" alt="OTTO Logo" class="logo">
            </a>
        </header>
        <ul>
            <li><a href="#" id="home-display">HOME</a></li>
            <li><a href="{% url 'main_platform' 'musinsa' %}" id="women-link">WOMEN</a></li>
            <li><a href="{% url 'main_platform' 'musinsa' %}" id="men-link">MEN</a></li>
            <script src="{% static 'main/js/scripts.js' %}"></script>
        </ul>
    </div>
    <div class="right-content">
        <button type="submit" class="login-button" onclick="document.location.href='{% url 'users:login' %}'">Login
        </button>
    </div>
</div>

<div class="sidebar">
    <h2>의류 사이트</h2>
    <ul>
        <li><a href="{% url 'main_platform' 'musinsa' %}" id="musinsa">무신사</a></li>
        <li><a href="{% url 'main_platform' '29cm' %}" id="29cm">29cm</a></li>
        <li><a href="{% url 'main_platform' 'zigzag' %}" id="zigzag">zigzag</a></li>
    </ul>
</div>

<div class="content" id="home">
    {% comment %}
    <div>
        <h1>사이즈 기반 의류 추천 플랫폼, OTTO에 오신 것을 환영합니다!</h1>
        <br>
        <h2>사용 방법</h2>
        <ol id="how-to-use">
            <li><strong>회원가입</strong>을 통해 자신의 신체 사이즈를 입력합니다.</li>
            <li>상단 메뉴에서 <strong>"WOMEN"</strong> 또는 <strong>"MEN"</strong>을 선택하여 카테고리를 선택합니다.</li>
            <li>입력한 사이즈를 기반으로 추천된 의류 목록을 확인하고, 원하는 옷을 선택합니다.</li>
            <li>추천된 의류를 통해 자신의 스타일을 완성하세요!</li>
        </ol>
        <br>
        <br>
        <div class="alert alert-danger" role="alert">
            <strong>팁:</strong> 사이즈 입력 후에는 추천된 의류를 클릭하여 자세한 정보를 확인하고 구매할 수 있습니다.
        </div>
    </div>
    {% endcomment %}
    <div class="slider-container">
        <div class="slider-wrapper">
            <div class="slide">
                <img src="https://assets-global.website-files.com/60a3629e04f26d12caff56df/618dc361ac41ea01f35d31c5_%5B%EC%9D%B4%EB%AF%B8%EC%A7%80%201%5D%20%EB%AC%B4%EC%8B%A0%EC%82%AC%2C%20%EB%B8%8C%EB%9E%9C%EB%93%9C%20%EB%AE%A4%EC%A6%88%20%EC%A0%95%ED%98%B8%EC%97%B0%EC%9D%98%20FW%20%EB%AA%A8%EB%85%B8%ED%86%A4%20%ED%99%94%EB%B3%B4%20%EA%B3%B5%EA%B0%9C.jpg"
                     alt="Image 1">
            </div>
            <div class="slide">
                <img src="https://letter.wepick.kr/wp-content/uploads/2023/05/AXSLCz.webp" alt="Image 2">
            </div>
            <div class="slide">
                <img src="https://cdnimage.dailian.co.kr/news/202303/news_1678666967_1210892_m_1.jpeg" alt="Image 3">
            </div>
            <div class="slide">
                <img src="https://cdn.asiaa.co.kr/news/photo/202302/115049_128675_130.jpg" alt="Image 4">
            </div>
            <div class="slide">
                <img src="https://i.ytimg.com/vi/9x5AoAwPAK4/maxresdefault.jpg" alt="Image 5">
            </div>
            <div class="slide">
                <img src="https://miro.medium.com/v2/resize:fit:1400/1*Ky_3nRQHr5m3kMQkTduanQ.png" alt="Image 6">
            </div>
            <div class="slide">
                <img src="https://dtd31o1ybbmk8.cloudfront.net/photos/d4b3328c6c7abd01585d9d0c4a044212/thumb.jpg"
                     alt="Image 7">
            </div>
            <div class="slide">
                <img src="https://storage.heypop.kr/assets/2022/08/24103858/1-7.jpg" alt="Image 8">
            </div>
            <div class="slide">
                <img src="https://cdn.prod.website-files.com/60a3629e04f26d12caff56df/65e586ff8be4c3781d7b382f_%5B%EC%9D%B4%EB%AF%B8%EC%A7%80%5D%2029CM%20%EC%9A%B0%EB%A8%BC%ED%8C%A8%EC%85%98%EB%B7%B0.jpg"
                     alt="Image 9">
            </div>
        </div>
        <button class="prev-slide">‹</button>
        <button class="next-slide">›</button>
        <ul class="slide_pagination"></ul>
    </div>
</div>
<script src="{% static 'main/js/platform_sidebar.js' %}"></script>
<script src="{% static 'main/js/banner.js' %}"></script>
</body>
</html>

mysite/main/templates/main/logged_in.html
{% extends "main/main.html" %}
{% load static %}

{% block gender_select %}
<li><a href="#" id="home-display">HOME</a></li>
{% csrf_token %}
{% if gender == 'female' %}
<li><a href="#" id="women-link">WOMEN</a></li>
<script src="{% static 'main/js/female.js' %}"></script>
{% else %}
<li><a href="#" id="men-link">MEN</a></li>
<script src="{% static 'main/js/male.js' %}"></script>
{% endif %}
{% endblock %}

{% block user_info %}
<p class="username-welcome">{{ user.username }} 고객님, 환영합니다!</p>
<form method="post" action="{% url 'users:logout' %}">
    {% csrf_token %}
    <button type="submit" class="login-button">Logout</button>
</form>
{% endblock %}

{% if gender == 'female' %}
{% block women_product_h2 %}
<div>
    <h2>{{ user.username }} 고객님 맞춤 사이즈 추천 결과입니다.</h2>
</div>
{% endblock %}
{% else %}
{% block men_product_h2 %}
<div>
    <h2>{{ user.username }} 고객님 맞춤 사이즈 추천 결과입니다.</h2>
</div>
{% endblock %}
{% endif %}

mysite/main/templates/main/logged_out.html
{% extends "main/main.html" %}
{% load static %}

{% block gender_select %}
<li><a href="#" id="home-display">HOME</a></li>
<li><a href="#" id="women-link">WOMEN</a></li>
<li><a href="#" id="men-link">MEN</a></li>
<script src="{% static 'main/js/scripts.js' %}"></script>
{% endblock %}

{% block user_info %}
<button type="submit" class="login-button" onclick="document.location.href='{% url 'users:login' %}'">Login</button>
{% endblock %}

{% block women_product_h2_out %}
<div>
    <h2>평균 여성 키(162cm)와 몸무게(56kg)로 추천된 결과입니다.</h2>
</div>
{% endblock %}

{% block men_product_h2_out %}
<div>
    <h2>평균 남성 키(174cm)와 몸무게(69kg)로 추천된 결과입니다.</h2>
</div>
{% endblock %}

mysite/main/templates/main/main.html
<!doctype html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>의류 추천 사이트, otto</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Stylish&display=swap" rel="stylesheet">
</head>

<body>
<div class="hero">
    <div class="left-content">
        <header>
            <a href="/" class="home">
                <img src="{% static 'main/images/otto_logo1.png' %}" alt="OTTO Logo" class="logo">
            </a>
        </header>
        <ul>
            {% block gender_select %}
            {% endblock %}
        </ul>
    </div>
    <div class="right-content">
        {% block user_info %}
        {% endblock %}
    </div>
</div>

<div class="sidebar">
    <h2>의류 사이트</h2>
    <ul>
        <li><a href="{% url 'main_platform' 'musinsa' %}" id="musinsa">무신사</a></li>
        <li><a href="{% url 'main_platform' '29cm' %}" id="29cm">29cm</a></li>
        <li><a href="{% url 'main_platform' 'zigzag' %}" id="zigzag">zigzag</a></li>
    </ul>
</div>

<div class="content" id="home">
    <div class="slider-container">
        <div class="slider-wrapper">
            <div class="slide">
                <img src="https://assets-global.website-files.com/60a3629e04f26d12caff56df/618dc361ac41ea01f35d31c5_%5B%EC%9D%B4%EB%AF%B8%EC%A7%80%201%5D%20%EB%AC%B4%EC%8B%A0%EC%82%AC%2C%20%EB%B8%8C%EB%9E%9C%EB%93%9C%20%EB%AE%A4%EC%A6%88%20%EC%A0%95%ED%98%B8%EC%97%B0%EC%9D%98%20FW%20%EB%AA%A8%EB%85%B8%ED%86%A4%20%ED%99%94%EB%B3%B4%20%EA%B3%B5%EA%B0%9C.jpg"
                     alt="Image 1">
            </div>
            <div class="slide">
                <img src="https://letter.wepick.kr/wp-content/uploads/2023/05/AXSLCz.webp" alt="Image 2">
            </div>
            <div class="slide">
                <img src="https://cdnimage.dailian.co.kr/news/202303/news_1678666967_1210892_m_1.jpeg" alt="Image 3">
            </div>
            <div class="slide">
                <img src="https://cdn.asiaa.co.kr/news/photo/202302/115049_128675_130.jpg" alt="Image 4">
            </div>
            <div class="slide">
                <img src="https://i.ytimg.com/vi/9x5AoAwPAK4/maxresdefault.jpg" alt="Image 5">
            </div>
            <div class="slide">
                <img src="https://miro.medium.com/v2/resize:fit:1400/1*Ky_3nRQHr5m3kMQkTduanQ.png" alt="Image 6">
            </div>
            <div class="slide">
                <img src="https://dtd31o1ybbmk8.cloudfront.net/photos/d4b3328c6c7abd01585d9d0c4a044212/thumb.jpg"
                     alt="Image 7">
            </div>
            <div class="slide">
                <img src="https://storage.heypop.kr/assets/2022/08/24103858/1-7.jpg" alt="Image 8">
            </div>
            <div class="slide">
                <img src="https://cdn.prod.website-files.com/60a3629e04f26d12caff56df/65e586ff8be4c3781d7b382f_%5B%EC%9D%B4%EB%AF%B8%EC%A7%80%5D%2029CM%20%EC%9A%B0%EB%A8%BC%ED%8C%A8%EC%85%98%EB%B7%B0.jpg"
                     alt="Image 9">
            </div>
        </div>
        <button class="prev-slide">‹</button>
        <button class="next-slide">›</button>
        <ul class="slide_pagination"></ul>
    </div>
</div>
{% if gender %}
{% if gender == 'female' %}
<div class="content" id="women-content">
    {% block women_product_h2 %}
    {% endblock %}
    <div>
        <p class="top-women-p">상의</p>
    </div>
    {% include "main/product_section.html" with product=top %}
    <div>
        <p class="bottom-women-p">하의</p>
    </div>
    {% include "main/product_section.html" with product=bottom %}
</div>
{% else %}
<div class="content" id="men-content">
    {% block men_product_h2 %}
    {% endblock %}
    <div>
        <p class="top-men-p">상의</p>
    </div>
    {% include "main/product_section.html" with product=top %}
    <div>
        <p class="bottom-men-p">하의</p>
    </div>
    {% include "main/product_section.html" with product=bottom %}
</div>
{% endif %}
{% else %}
<div class="content" id="women-content">
    {% block women_product_h2_out %}
    {% endblock %}
    <div>
        <p class="top-women-p">상의</p>
    </div>
    {% include "main/product_section_loggedout.html" with product=women_top %}
    <div>
        <p class="bottom-women-p">하의</p>
    </div>
    {% include "main/product_section_loggedout.html" with product=women_bottom %}
</div>
<div class="content" id="men-content">
    {% block men_product_h2_out %}
    {% endblock %}
    <div>
        <p class="top-men-p">상의</p>
    </div>
    {% include "main/product_section_loggedout.html" with product=men_top %}
    <div>
        <p class="bottom-men-p">하의</p>
    </div>
    {% include "main/product_section_loggedout.html" with product=men_bottom %}
</div>
{% endif %}
<script src="{% static 'main/js/platform_sidebar.js' %}"></script>
<script src="{% static 'main/js/banner.js' %}"></script>
</body>
</html>

mysite/main/templates/main/product_section.html
<div>
    <div class="scroll-container">
        {% for item in product %}
        <a class="product-container" href="{{ item.product.description }}">
            <img src="{{ item.product.image_url }}" alt="{{ item.product.product_name }}">
            <div class="product-name">{{ item.product.product_name }}</div>
            <div class="product-size">
                {% if item.size == '-' %}
                {{ item.product.size }}
                {% else %}
                {{ item.size }}
                {% endif %}
            </div>
            {% if item.score %}
            <div class="product-score">추천 점수: {{ item.score }}</div>
            {% endif %}
        </a>
        {% endfor %}
    </div>
</div>

mysite/main/templates/main/product_section_loggedout.html
<div>
    <div class="scroll-container">
        {% for item in product %}
        <a class="product-container" href="{{ item.description }}">
            <img src="{{ item.image_url }}" alt="{{ item.product_name }}">
            <div class="product-name">{{ item.product_name }}</div>
            <div class="product-size">{{ item.size }}</div>
        </a>
        {% endfor %}
    </div>
</div>