mysite/main/urls.py
from django.urls import path

from . import views as main_view

urlpatterns = [
    path('', main_view.index, name='index'),
    path('<str:platform>/', main_view.main_platform, name='main_platform'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls'), name="index"),
    path("admin/", admin.site.urls),
    path('users/', include('users.urls'), name='users')
]

mysite/users/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path

from . import views as users_view

app_name = 'users'
urlpatterns = [
    path('login/', users_view.CustomLoginView.as_view(), name="login"),
    path('logout/', auth_view.LogoutView.as_view(next_page='/'), name="logout"),
    path('signup/', users_view.signup, name='signup')
]

mysite/users/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import IntegrityError
from django.db import models
from django.utils import timezone
from products.models import ProductTable


class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('male', '남'),
        ('female', '여'),
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    height = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()


class UserMLResult(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductTable, on_delete=models.CASCADE)
    size = models.CharField(max_length=100, blank=True, null=True)
    score = models.FloatField()
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'product')

    @staticmethod
    def create(user: CustomUser, product: ProductTable, size: str, score: float):
        try:
            return UserMLResult.objects.create(
                user=user,
                product=product,
                size=size,
                score=score
            )
        except IntegrityError as e:
            return None

    @staticmethod
    def needs_api_call(user):
        last_result = UserMLResult.objects.filter(user=user).order_by('-timestamp').first()

        if not last_result:
            return True

        now = timezone.now()

        time_diff = now - last_result.timestamp

        if time_diff > timedelta(days=1):
            return True

        return False

    @staticmethod
    def get_ml_results(user):
        pass

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class SignUpForm(UserCreationForm):
    gender = forms.ChoiceField(choices=CustomUser.GENDER_CHOICES, required=True)
    height = forms.FloatField(required=True)
    weight = forms.FloatField(required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2', 'gender', 'height', 'weight')
        labels = {
            'username': '아이디'
        }

mysite/users/views.py
import requests
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.shortcuts import render
from products.models import ProductTable
from requests.exceptions import Timeout

from .forms import SignUpForm
from .models import UserMLResult


def request_get(api_url, params):
    try:
        res = requests.get(api_url, params=params, timeout=3)
        return res
    except Timeout as e:
        return None


def connection_test(api_url):
    try:
        requests.get(api_url, timeout=10)
        return True
    except Timeout as e:
        return False
    except ConnectionError as e:
        return False


def load_ml_results(user):
    host = settings.ML_API_HOST
    api_url = f"http://{host}/predict"
    connection_url = f"http://{host}/connection"

    if not UserMLResult.needs_api_call(user):
        return

    if not connection_test(connection_url):
        return

    gender = '남성' if user.gender == 'male' else '여성'
    params = {
        "gender": gender,
        "weight": user.weight,
        "height": user.height
    }
    products = []
    platforms = ['musinsa', '29cm', 'zigzag']
    categories = ['top', 'bottom']
    for platform in platforms:
        for category in categories:
            temp = ProductTable.get_product_filter_by_gender(platform=platform, category=category, gender=user.gender)
            products.extend(temp)

    for product in products:
        params['product_name'] = product.product_name
        res = request_get(api_url, params)
        size, score = process_prediction_result(res)
        UserMLResult.create(user=user, product=product, size=size, score=score)


def process_prediction_result(res):
    if res is None:
        return '-', 0
    res = res.json()
    if not res or not res['success']:
        return '-', 0
    return res['prediction'], res['prob']


class CustomLoginView(auth_views.LoginView):
    template_name = "users/login.html"

    def form_valid(self, form):
        user = form.get_user()
        load_ml_results(user)
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.get(self.request)


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            load_ml_results(user)
            return redirect('main_platform', platform='musinsa')
    else:
        form = SignUpForm()
    return render(request, "users/signup.html", {"form": form})

mysite/users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <title>OTTO</title>
    <link rel="stylesheet" href="{% static 'base/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="hero">
        <div class="left-content">
            <header>
                <a href="/" class="home">
                    <img src="{% static 'main/images/otto_logo1.png' %}" alt="OTTO Logo" class="logo">
                </a>
            </header>
        </div>
    </div>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

mysite/users/templates/users/login.html
{% extends "users/base.html" %}
{% block content %}

<div class="login-wrapper">
    <h2>로그인</h2>
    <form method="post" action="{% url 'users:login' %}" id="login-form">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ request.POST.username|default_if_none:'' }}" placeholder="사용자ID">
        </div>
        <div class="mb-3">
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ request.POST.password|default_if_none:'' }}" placeholder="비밀번호">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    <div class="signup-button-wrapper">
        <button type="button" class="signup-button" onclick="document.location.href='{% url 'users:signup' %}'">회원가입
        </button>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/signup.html
{% extends "users/base.html" %}
{% load custom_filters %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>회원가입</title>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            {% if messages %}
                {% for message in messages %}
                    alert('{{ message }}');
                {% endfor %}
            {% endif %}
        });
    </script>
</head>
<body>
    <div class="signup-wrapper">
        <h2>회원가입</h2>
        <form method="post" class="form-group">
            {% csrf_token %}
            <div class="form-text-input">
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" id="id_username"
                           value="{{ form.username.value|default_if_none:'' }}" placeholder="ID">
                    {% if form.username.errors %}
                        <div class="form-error">
                            {{ form.username.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password1" id="id-password1"
                           value="{{ form.password1.value|default_if_none:'' }}" placeholder="비밀번호">
                    {% if form.password1.errors %}
                        <div class="form-error">
                            {{ form.password1.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password2" id="id-password2"
                           value="{{ form.password2.value|default_if_none:'' }}" placeholder="비밀번호 확인">
                    {% if form.password2.errors %}
                        <div class="form-error">
                            {{ form.password2.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <input type="text" class="form-control" name="height" id="id-height"
                           value="{{ form.height.value|default_if_none:'' }}" placeholder="키">
                    {% if form.height.errors %}
                        <div class="form-error">
                            {{ form.height.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <input type="text" class="form-control" name="weight" id="id-weight"
                           value="{{ form.weight.value|default_if_none:'' }}" placeholder="몸무게">
                    {% if form.weight.errors %}
                        <div class="form-error">
                            {{ form.weight.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="form-select-input">
                <div class="mb-3">
                    <select name="gender" id="id_gender" class="form-control form-gender-select">
                        <option value="" disabled {% if not form.gender.value %}selected{% endif %}>성별 선택</option>
                        <option value="male" {% if form.gender.value == 'male' %}selected{% endif %}>남</option>
                        <option value="female" {% if form.gender.value == 'female' %}selected{% endif %}>여</option>
                    </select>
                    {% if form.gender.errors %}
                        <div class="form-error">
                            {{ form.gender.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
                <button type="submit" class="signup-form-button-wrapper">가입하기</button>
        </form>
    </div>
</body>
</html>
{% endblock %}